name = "iowa-print-solutions"
compatibility_date = "2024-08-01"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
dir = "./dist"
main = "./index.html"

# This is specifically for Cloudflare Pages
pages_build_output_dir = "./dist"