name = "iowa-print-solutions"
compatibility_date = "2024-08-01"

# Pages configuration
[pages]
build_output_dir = "./dist"
build_command = "npm run build"

# Build configuration for Cloudflare Pages
[build]
command = "npm run build"
publish = "dist"

# Environment variables for build
[env.production.vars]
NODE_ENV = "production"

# Compatibility settings for proper asset serving
compatibility_flags = ["nodejs_compat"]